linters:
  enable:
    - revive
    - errcheck # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - gofmt
    - gosimple # Linter for Go source code that specializes in simplifying a code
    - govet
    - unused