name: Go Test
on:
  pull_request:

env:
  GO_VERSION: 1.23.x
  GOLANGCI_LINT_VERSION: v1.61

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: go test
        run: go test ./...
